#!/usr/bin/env python3
"""
auto_post_cross_platform.py

Automated cross-platform posting for Dr. Lori Alexander's wellness brands.
Reads pending post files generated by the master orchestrator and schedules
them across Instagram, Facebook, and YouTube via Buffer's GraphQL API.

SCHEDULE SLOTS (ET, all outside quiet hours 10PM-6AM):
  Morning   7:00 AM  — education / authority / trust-building
  Afternoon 3:00 PM  — pain point / problem awareness
  Evening   7:00 PM  — conversion / CTA

USAGE:
  python3 auto_post_cross_platform.py --brand revitalize --slot morning
  python3 auto_post_cross_platform.py --brand reclaim --slot evening
  python3 auto_post_cross_platform.py --brand both --slot morning --dry-run

ENVIRONMENT VARIABLES:
  BUFFER_API_KEY        — Buffer API key (required for live posting)
  BUFFER_IG_CHANNEL_ID  — Buffer Instagram channel ID (optional, auto-discovered)
  BUFFER_FB_CHANNEL_ID   — Buffer Facebook channel ID (optional, auto-discovered)
  BUFFER_YT_CHANNEL_ID   — Buffer YouTube channel ID (optional, auto-discovered)

META COMPLIANCE:
  All captions are pre-filtered to ensure they contain NO prohibited words:
  transform, reverse, cure, heal, eliminate, restore, reset, detox, cleanse,
  boost, guarantee, proven, limited time, act now, etc.
  See /Users/drlori/meta-compliance-audit.md for full prohibited words list.
"""

import argparse
import json
import os
import re
import sys
import time
from datetime import datetime, timedelta, timezone
from pathlib import Path
from zoneinfo import ZoneInfo

import urllib.request
import urllib.error
import json as _json

BUFFER_API = "https://api.buffer.com"

# ─── Meta Compliance Prohibited Words ───────────────────────────
# Only block words when used as MEDICAL/HEALTH CLAIMS, not normal English.
# "cure" is allowed in the disclaimer ("not intended to diagnose, treat, cure...")
# "transformation" is allowed as normal English ("imagine the transformation")
# "restore" is allowed as normal English ("restore your confidence")
# We block the CLAIM forms: "transform your body", "cure your...", "reverse aging", etc.
PROHIBITED_PHRASES = [
    # Medical claims — only blocked when followed by health-related nouns
    "transform your body", "transform your health", "transform your life",
    "reverse aging", "reverse the aging", "reverse symptoms", "reverse disease",
    "cure your", "cured of", "cure for",
    "heal your", "healing your", "healed from",
    "eliminate your", "eliminating your",
    "detox your", "detoxify your body", "cleanse your body",
    "boost your metabolism", "boost testosterone", "boost your immune",
    "boost your energy", "boost your hormones",
    "balance your hormones", "balance hormones",
    # Absolute claims (always blocked)
    "guarantee", "guaranteed", "proven", "scientifically proven",
    "100%", "foolproof", "failproof", "effortless",
    "miracle", "miraculous", "breakthrough", "secret formula",
    "revolutionary", "game-changer",
    # Urgency / pressure (always blocked)
    "limited time", "act now", "don't miss out",
    "last chance", "before it's gone",
    "ends tonight", "ends today", "doors closing", "hurry",
    # Body shaming (always blocked)
    "flabby", "saggy", "wrinkled", "sluggish",
    "out of shape", "let yourself go",
]

# Words that are OK as part of brand names (proper nouns)
BRAND_NAME_EXCEPTIONS = ["Revitalize", "Reclaim", "Thrive"]

ET = ZoneInfo("America/New_York")


def check_compliance(text: str) -> tuple:
    """Check text for prohibited medical/health claims. Returns (is_compliant, violations_list).
    
    Only flags words/phrases when used as health claims, NOT when used in:
    - The mandatory disclaimer ("not intended to diagnose, treat, cure...")
    - Normal English ("imagine the transformation", "restore your confidence")
    - Brand names ("Revitalize & Thrive Now", "Reclaim & Rise")
    """
    text_lower = text.lower()
    violations = []
    for phrase in PROHIBITED_PHRASES:
        if phrase in text_lower:
            # Check if it's part of a brand name
            is_brand = any(
                exc.lower() in text_lower and exc in text
                for exc in BRAND_NAME_EXCEPTIONS
            )
            if not is_brand:
                violations.append(phrase)
    return (len(violations) == 0, violations)


def graphql(api_key: str, query: str, variables: dict = None) -> dict:
    headers = {
        "Authorization": "Bearer " + api_key,
        "Content-Type": "application/json",
    }
    body = {"query": query}
    if variables:
        body["variables"] = variables
    body_bytes = json.dumps(body).encode("utf-8")
    req = urllib.request.Request(BUFFER_API, data=body_bytes, headers=headers, method="POST")
    wait = 60
    for attempt in range(6):
        try:
            resp = urllib.request.urlopen(req, timeout=15)
            return json.loads(resp.read().decode("utf-8"))
        except urllib.error.HTTPError as e:
            if e.code == 429:
                print(f"  Rate limited — sleeping {wait}s (attempt {attempt + 1}/6)")
                time.sleep(wait)
                wait = min(wait * 2, 300)
                req = urllib.request.Request(BUFFER_API, data=body_bytes, headers=headers, method="POST")
                continue
            print(f"  HTTP {e.code} error. Response: {e.read().decode('utf-8', errors='replace')[:1000]}")
            e.raise_for_status()
        except Exception as e:
            print(f"  Request error: {e}")
            raise
    return {}


def get_channels(api_key: str) -> dict:
    """Discover all connected Buffer channels."""
    query = "query { account { organizations { id name } } }"
    data = graphql(api_key, query)
    orgs = data["data"]["account"]["organizations"]
    if not orgs:
        sys.exit("ERROR: No Buffer organizations found")
    org_id = orgs[0]["id"]

    query = """
    query GetChannels($input: ChannelsInput!) {
      channels(input: $input) { id name service }
    }
    """
    data = graphql(api_key, query, {"input": {"organizationId": org_id}})
    channels = {}
    for ch in data["data"]["channels"]:
        svc = ch["service"]
        if svc not in channels:
            channels[svc] = ch["id"]
        print(f"  Channel: {ch['service']} — {ch['name']} ({ch['id']})")
    return channels


def schedule_post(api_key: str, channel_id: str, text: str,
                  due_at: datetime, image_url: str = None,
                  platform: str = "instagram", dry_run: bool = False) -> dict:
    """Schedule a post via Buffer GraphQL API."""
    if dry_run:
        return {"dry_run": True, "preview": text[:80]}

    mutation = """
    mutation CreatePost($input: CreatePostInput!) {
      createPost(input: $input) {
        ... on PostActionSuccess { post { id text dueAt status } }
        ... on MutationError { message }
      }
    }
    """

    post_input = {
        "channelId": channel_id,
        "text": text,
        "mode": "customScheduled",
        "schedulingType": "automatic",
        "dueAt": due_at.strftime("%Y-%m-%dT%H:%M:%S.000Z"),
    }

    # Add image asset if provided (Instagram requires an image)
    if image_url:
        post_input["assets"] = [{"image": {"url": image_url}}]

    # Add platform-specific metadata
    if platform == "instagram":
        post_input["metadata"] = {
            "instagram": {
                "type": "post",
                "shouldShareToFeed": True
            }
        }
    elif platform == "facebook":
        post_input["metadata"] = {
            "facebook": {
                "type": "post"
            }
        }

    post_input["saveToDraft"] = True  # Save as draft for review before publishing

    body = json.dumps({"query": mutation, "variables": {"input": post_input}}).encode("utf-8")
    headers = {
        "Authorization": "Bearer " + api_key,
        "Content-Type": "application/json",
    }
    req = urllib.request.Request(BUFFER_API, data=body, headers=headers, method="POST")

    try:
        resp = urllib.request.urlopen(req, timeout=15)
        data = json.loads(resp.read().decode("utf-8"))

        if "errors" in data:
            print(f"  GraphQL errors: {data['errors']}")
            return {}

        result = data.get("data", {}).get("createPost", {})
        if "message" in result:
            print(f"  Buffer error: {result['message']}")
            return {}

        return result.get("post", {})
    except Exception as e:
        print(f"  Request error: {e}")
        return {}


def load_pending_posts(brand: str, slot: str) -> list:
    """Load pending posts from JSON files generated by master_orchestrator."""
    repo = Path("/Users/drlori/revitalize-and-thrive-now")
    today = datetime.now(ET).strftime("%Y-%m-%d")
    pattern = f"pending-posts-{today}-{slot}.json"
    filepath = repo / "data" / pattern

    if not filepath.exists():
        print(f"No pending posts file found at {filepath}")
        return []

    with open(filepath) as f:
        posts = json.load(f)

    if brand == "both":
        return posts
    return [p for p in posts if p.get("brand") == brand]


def main():
    parser = argparse.ArgumentParser(
        description="Cross-platform auto-posting via Buffer"
    )
    parser.add_argument("--brand", required=True,
                        choices=["revitalize", "reclaim", "both"])
    parser.add_argument("--slot", required=True,
                        choices=["morning", "afternoon", "evening"])
    parser.add_argument("--api-key", default=os.environ.get("BUFFER_API_KEY", ""))
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    if not args.api_key and not args.dry_run:
        sys.exit("ERROR: BUFFER_API_KEY required (or use --dry-run)")

    # Load pending posts
    posts = load_pending_posts(args.brand, args.slot)
    if not posts:
        print(f"No pending posts for brand={args.brand}, slot={args.slot}")
        return

    print(f"\n{'='*60}")
    print(f"CROSS-PLATFORM AUTO-POSTING — {args.slot.upper()} SLOT")
    print(f"Brand: {args.brand} | Posts: {len(posts)} | Dry run: {args.dry_run}")
    print(f"{'='*60}\n")

    # Load channel IDs from env or config file
    ig_id_revitalize = os.environ.get("BUFFER_IG_CHANNEL_ID_REVITALIZE", "")
    ig_id_reclaim = os.environ.get("BUFFER_IG_CHANNEL_ID_RECLAIM", "")
    fb_id = os.environ.get("BUFFER_FB_CHANNEL_ID", "")
    yt_id = os.environ.get("BUFFER_YT_CHANNEL_ID", "")

    # Fallback: load from config file if env vars not set
    if not ig_id_revitalize:
        config_path = Path.home() / ".buffer-config"
        if config_path.exists():
            for line in config_path.read_text().splitlines():
                if line.startswith("BUFFER_IG_CHANNEL_ID_REVITALIZE="):
                    ig_id_revitalize = line.split("=", 1)[1].strip()
                elif line.startswith("BUFFER_IG_CHANNEL_ID_RECLAIM="):
                    ig_id_reclaim = line.split("=", 1)[1].strip()
                elif line.startswith("BUFFER_FB_CHANNEL_ID="):
                    fb_id = line.split("=", 1)[1].strip()
                elif line.startswith("BUFFER_YT_CHANNEL_ID=") and not yt_id:
                    yt_id = line.split("=", 1)[1].strip()

    if not args.dry_run and not ig_id_revitalize and not ig_id_reclaim:
        print("Discovering Buffer channels...")
        channels = get_channels(args.api_key)
        ig_id_revitalize = channels.get("instagram", "")  # Fallback
        # Manually assign based on name matching
        if "instagram" in channels:
            ig_id_revitalize = channels["instagram"]
        print("  WARNING: Could not distinguish Revitalize vs Reclaim Instagram channels.")
        print("  Set BUFFER_IG_CHANNEL_ID_REVITALIZE and BUFFER_IG_CHANNEL_ID_RECLAIM env vars.")

    # Schedule time = now + 5 minutes (to allow processing)
    schedule_at = datetime.now(timezone.utc) + timedelta(minutes=5)

    success_count = 0
    for post in posts:
        brand = post.get("brand", "revitalize")
        caption = post.get("caption", "")
        image_url = post.get("image_url", "")

        # ─── Compliance Check ───────────────────────────────
        is_compliant, violations = check_compliance(caption)
        if not is_compliant:
            print(f"⚠ COMPLIANCE VIOLATION in {brand} post:")
            print(f"  Violations: {violations}")
            print(f"  Caption preview: {caption[:100]}...")
            print(f"  SKIPPING — this post needs revision before publishing.\n")
            continue

        # ─── Add disclaimer if not present ────────────────────
        disclaimer = (
            "\n\n📋 Educational workbook. Not intended to diagnose, treat, "
            "cure, or prevent any disease. Individual experiences vary. "
            "Consult a healthcare professional before making health changes."
        )
        if "educational workbook" not in caption.lower():
            caption += disclaimer

        # ─── Add CTA ────────────────────────────────────────
        cta = "\n\n🔗 Link in bio to explore the collection."
        if "link in bio" not in caption.lower():
            caption += cta

        print(f"✓ {brand.upper()} — Compliant")
        print(f"  Preview: {caption[:120]}...")
        print(f"  Image: {image_url[:80] if image_url else 'NONE'}")

        if not args.dry_run:
            # Post to Instagram — use correct channel for each brand
            brand_ig_id = ig_id_revitalize if brand == "revitalize" else ig_id_reclaim
            if brand_ig_id:
                result = schedule_post(args.api_key, brand_ig_id, caption,
                                        schedule_at, image_url, platform="instagram")
                if result:
                    print(f"  ✅ Instagram scheduled (ID: {result.get('id', 'N/A')})")
                    success_count += 1
                else:
                    print(f"  ❌ Instagram failed")

            # Post to Facebook
            if fb_id:
                fb_caption = caption + "\n\nExplore: https://lccrichards.github.io/revitalize-and-thrive-now/shop.html"
                result = schedule_post(args.api_key, fb_id, fb_caption,
                                        schedule_at, image_url, platform="facebook")
                if result:
                    print(f"  ✅ Facebook scheduled")

            # Post to YouTube (if channel exists)
            if yt_id:
                yt_caption = f"{post.get('title', '')}\n\n{caption}"
                result = schedule_post(args.api_key, yt_id, yt_caption,
                                        schedule_at, image_url)
                if result:
                    print(f"  ✅ YouTube scheduled")

            time.sleep(4)  # Rate limit buffer

        print()

    print(f"{'='*60}")
    print(f"Done. {success_count} posts scheduled across platforms.")
    print(f"{'='*60}")


if __name__ == "__main__":
    main()
